"""seed test user and admin

Revision ID: 8b8b58a2456b
Revises: 19bb38dac297
Create Date: 2026-04-26 16:07:18.534257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b8b58a2456b"
down_revision: Union[str, Sequence[str], None] = "19bb38dac297"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        INSERT INTO user_accounts (id, email, full_name, hashed_password)
        VALUES (1, 'user@example.com', 'Test User', '$2b$12$.aV8W/LvJtDnlbUAxBPiLeYMXgarkml/DJ.1Q.OwJpKWLtGd0lcM.')
    """
    )

    op.execute(
        """
        INSERT INTO admin_accounts (id, email, full_name, hashed_password)
        VALUES (1, 'admin@example.com', 'Test Admin', '$2b$12$.aV8W/LvJtDnlbUAxBPiLeYMXgarkml/DJ.1Q.OwJpKWLtGd0lcM.')
    """
    )

    op.execute(
        """
        INSERT INTO accounts (id, user_id, balance)
        VALUES (1, 1, 0.00)
    """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
